[versions]
accompanistPermissions = "0.37.3"
agp = "8.12.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidXActivity = "1.11.0"
androidXLifecycle = "2.9.4"
compose = "1.9.0"
composeWebViewMultiplatformDesktop = "2.0.3"
dokka = "2.1.0"
googleMapsCompose = "6.12.2"
googleMapsComposeUtils = "6.12.2"
kcef = "2024.04.20.4"
kotlin = "2.2.20"
kotlinXSerializationJson = "1.9.0"
mavenPublish = "0.34.0"
playServicesMaps = "19.2.0"
secretsGradlePlugin = "2.0.1"
jetbrainsKotlinJvm = "2.2.20"
kotlinXCoroutines = "1.10.2"

[libraries]
androidX-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidXActivity" }
kevinnZou-composeWebViewMultiplatformDesktop = { module = "io.github.kevinnzou:compose-webview-multiplatform-desktop", version.ref = "composeWebViewMultiplatformDesktop" }
google-accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
google-android-gms-playServicesMaps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
google-android-libraries-mapsPlatform-secretsGradlePlugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
google-maps-android-mapsCompose = { module = "com.google.maps.android:maps-compose", version.ref = "googleMapsCompose" }
google-maps-android-mapsComposeUtils = { module = "com.google.maps.android:maps-compose-utils", version.ref = "googleMapsComposeUtils" }
jetBrains-androidX-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidXLifecycle" }
jetBrains-androidX-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidXLifecycle" }
jetBrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kcef = { module = "dev.datlag:kcef", version.ref = "kcef" }
jetBrains-kotlinX-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinXCoroutines" }
jetBrains-kotlinX-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinXSerializationJson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetBrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetBrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
jetBrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetBrains-kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
jetBrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
